### ISSUE TITLE
Potential Bug in Vertices Score

### ISSUE THREAD

**Issue by EvanXiaa** [MelbourneFuzzingHub/aflteam#2]
Hi author,

It seems that we should set an upper bound for the score of vertices in lukes_partitioning.py, or the score of a single node may exceed the max_size in lukes_partitioning() and result in a NoneType Error in python.

**Comment by thuanpv** [comment]
Thanks @Anderson-Xia for reporting this issue. It will be fixed in our next release. It seems there are other things that could lead to the NoneType Error while calling lukes' algorithm.

**Comment by MelbourneFuzzingHub** [comment]
I hope this recent commit https://github.com/MelbourneFuzzingHub/aflteam/commit/36948dc814656d9729299ef79461479cb400649d can fix the issue. Thanks!

**Comment by EvanXiaa** [comment]
Thanks @MelbourneFuzzingHub for replying, I think it works well.
